### ISSUE TITLE
Get more accurage `hg` revision sha1s for unpushed commits

### ISSUE THREAD

**Issue by mystor** [mystor/phlay#10]
Currently we can only get hg sha1s for commits which have already been published to m-c, and not for commits which are local-only. This is slightly unfortunate, because ideally we could send the correct sha1 information down with our diffs such that we can reconstruct better in the future.

@glandium, is there a way for me to generate the hg sha1s of a series of commits (I don't necessarily want to preserve the info in the git repository after I get that information). All I can think of doing right now is creating an bundle with `git cinnabar bundle --version=1 /tmppath/xxx commit..range` and then parsing the commit bundle format for the sha1s, or using `git cinnabar python` to directly call cinnabar methods.

**Comment by glandium** [comment]
I would advise against calling cinnabar methods directly, because there are no API stability guarantees, and I'll likely break whatever you'd be using in the future. `git cinnabar bundle` is the safest bet at the moment. Note that if you're okay having a dependency on mercurial, you can use `hg debugbundle` to extract the sha1s from the bundle.

**Comment by mystor** [comment]
Awesome, good to know. I didn't realize that `hg debugbundle` existed, and it sounds like exactly what I need :-) (although I imagine that the output format is somewhat volatile, because it seems like a debug helper command).

**Comment by mystor** [comment]
Ended up finding it easier to just parse the binary bundle format than the debugbundle output. Fixed in  5dcc42f

**Comment by glandium** [comment]
Just a note, since I saw you are using git cinnabar git2hg. Now that you're using bundle, you can actually avoid skip that, and get the parent sha1 from the bundle.

**Comment by mystor** [comment]
@glandium if I specify a range which doesn't have a pregenerated hg hash in the parent it doesn't work though, right?I'm calling git2hg to determine where the bundle range needs to start.

**Comment by glandium** [comment]
mmmm you're right.
