### ISSUE TITLE
Should not add dependencies on the parent commit of the first commit

### ISSUE THREAD

**Issue by glandium** [mystor/phlay#14]
(I'm now on the diffparser branch)

When I created https://phabricator.services.mozilla.com/D4748, it added a dependency on https://phabricator.services.mozilla.com/D4740, which is completely unrelated. Presumably, it did so because it happened to be the state of inbound when I rebased my commit before sending it to phabricator.

**Comment by mystor** [comment]
There is a flag (`--no-extern-deps`) which has this effect, but you're right it should probably be the default

**Comment by mystor** [comment]
Fixed by #13
