### ISSUE TITLE
Unable to land a patch that fixes DOS line endings

### ISSUE THREAD

**Issue by amccreight** [mystor/phlay#27]
I get a rebase error: https://lando.services.mozilla.com/revisions/D4156/13502/

This sounds like it could be related to issue #21.

**Comment by mystor** [comment]
Hmm, yes. It's likely that python is being clever and "helpfully" making the diff uniformly handle newlines.

@amccreight Could you send me the output of `git diff -U 65535 --patch --no-textconv --no-ext-diff --no-color commit..range` for that patch?

**Comment by amccreight** [comment]
I guess I don't understand what you mean, because I tried
  git diff -U 65535 --patch --no-textconv --no-ext-diff --no-color mozilla/central..4cfbe8097d52
and I got the error "error: short SHA1 65535 is ambiguous", so something isn't right.

**Comment by amccreight** [comment]
Ah, no space after the U, it looks like.

**Comment by mystor** [comment]
Fixed by #31
