### ISSUE TITLE
Deleted files don't have the right --- line

### ISSUE THREAD

**Issue by glandium** [mystor/phlay#28]
The raw diff for https://phabricator.services.mozilla.com/D5632 contains things like:

```
diff --git a/ b/
deleted file mode 100644
--- /dev/null
+++ /dev/null
```

for deleted files, which lando subsequently can't handle (for good reason).

Interesting file names in the non-raw view are correct.

**Comment by globau** [comment]
what's weird here is even the hunk that updated an existing file is malformed:

```
diff --git a/testing/mozharness/mozharness/mozilla/building/buildbase.py b/testing/mozharness/mozharness/mozilla/building/buildbase.py
--- /dev/null
+++ b/testing/mozharness/mozharness/mozilla/building/buildbase.py
@@ -416,8 +416,6 @@
         'fuzzing-debug': 'builds/releng_sub_%s_configs/%s_fuzzing_debug.py',
         'asan-and-debug': 'builds/releng_sub_%s_configs/%s_asan_and_debug.py',
         'asan-tc-and-debug': 'builds/releng_sub_%s_configs/%s_asan_tc_and_debug.py',
-        'lto-tc': 'builds/releng_sub_%s_configs/%s_lto_tc.py',
-        'lto-tc-and-debug': 'builds/releng_sub_%s_configs/%s_lto_tc_and_debug.py',
         'stat-and-debug': 'builds/releng_sub_%s_configs/%s_stat_and_debug.py',
         'code-coverage-debug': 'builds/releng_sub_%s_configs/%s_code_coverage_debug.py',
         'code-coverage-opt': 'builds/releng_sub_%s_configs/%s_code_coverage_opt.py',
```

**Comment by amccreight** [comment]
Yeah, the --- line doesn't seem to be set up correctly even in the normal case, which is stopping me from using Lando. It was working earlier, but maybe I was on an earlier revision of Phlay (previously, it was a single patch and now it is multiple patches, if that could make a difference). I've been trying to figure out where that might be generated in the code but I haven't found it yet.

**Comment by glandium** [comment]
Note that I've used lando successfully with patches uploaded by the same phlay revision that led to this error.

**Comment by amccreight** [comment]
Well, my patch fixed two bugs in the --- stuff, which fixed the problem I was seeing with a patch that deleted a file. If you are still seeing this issue with my patch, let me know.
