### ISSUE TITLE
`error user aborted` when typing Enter after `Proceed? (Y/n)`

### ISSUE THREAD

**Issue by jankeromnes** [mystor/phlay#3]
## Steps to reproduce:

```
$ phlay HEAD^^..HEAD
6991c277adad Bug 1234567 - Commit 1/2. r=reviewer
  Revision      https://phabricator-dev.allizom.org/D679
  Set Title     [...]

25762f8fb7dd Bug 1234567 - Commit 2/2. r=reviewer
  Revision      <<new>>
  Repository    mozilla-central
  Set Title     [...]

Proceed? (Y/n)
```

Then just press `Enter`.

## Expected

Proceeds.

## Actual behavior

Stops and prints `error user aborted`.

## Work around

When you explicitly enter `Y` before pressing `Enter`, it works as expected.

**Comment by jankeromnes** [comment]
Also, thanks a lot for creating `phlay`! I really look forward to being able to upload commit series to review again.

**Comment by mystor** [comment]
This is just caused by my super simplistic prompt code here: https://github.com/mystor/phlay/blob/ba0bccfb111192f9439c889765ec7272e3901f03/phlay#L419 which checks that the result equals `Y` exactly. I'd need to make it also accept the empty string.

**Comment by jankeromnes** [comment]
Thank you for fixing this so quickly! :100:
