### ISSUE TITLE
Punctuations are stripped at the end of the commit title

### ISSUE THREAD

**Issue by aethanyc** [mystor/phlay#37]
phlay seems to strip punctuations for the commit title, but I'd like to have a period at the end of the title to separate `r=XXX`. Perhaps it would be good to customize the behavior? Or just strip whitespace, but not other symbols?

https://github.com/mystor/phlay/blob/f2e0afadc7acc7467b1226126cdc0bf96f5f0d5f/phlay#L593-L594

**Comment by mystor** [comment]
I do this stripping because of the separation of r=XXX, I was trying to not include the r= section in the revision title. Is this causing a problem with the actual commit messages landed with lando or similar?

**Comment by aethanyc** [comment]
Yes, it affects the commit message landed with lando. If the local commit message is either `Bug 12345 - Commit title.` or `Bug 12345 - Commit title. r=XXX`

It ends up getting a revision title as `Bug 12345 - Commit title` (without the period at the end).

So lando will commit it as `Bug 12345 - Commit title r=XXX`

**Comment by aethanyc** [comment]
Thank you for fixing this!
