### ISSUE TITLE
hunks missing `addLines` and `delLines`

### ISSUE THREAD

**Issue by globau** [mystor/phlay#39]
phlay doesn't set `addLines` or `delLines` in the `hunk` objects it sends to `differential.creatediff`, resulting in data missing from the phabricator ui.

via bug https://bugzilla.mozilla.org/show_bug.cgi?id=1497989

https://github.com/mystor/phlay/blob/master/phlay#L173-L180

here's a php `var_dump` of what arc sends:

```
        array(9) {
          ["oldOffset"]=>
          string(1) "1"
          ["newOffset"]=>
          string(1) "0"
          ["oldLength"]=>
          string(2) "31"
          ["newLength"]=>
          string(1) "0"
          ["addLines"]=>
          int(0)
          ["delLines"]=>
          int(31)
          ["isMissingOldNewline"]=>
          bool(false)
          ["isMissingNewNewline"]=>
          bool(false)
          ["corpus"]=>
          string(362) "-hello pentester...
```

**Comment by mystor** [comment]
Thanks! Should be fixed in 7f400c7 (v0.1.3)
