### ISSUE TITLE
Add support for an away message warning

### ISSUE THREAD

**Issue by amccreight** [mystor/phlay#43]
You can mark yourself as away in Phabricator, which is supposed to display a warning when somebody flags you for review. This should be supported in Phabricator, which would likely involve showing some kind of message and then asking to confirm that yes, you still want to ask for review.

**Comment by mystor** [comment]
Looks like arcanist does something like this:

https://github.com/phacility/arcanist/blob/222800a86ed002c564e2760d6c5d9e93810b5b96/src/workflow/ArcanistDiffWorkflow.php#L1824-L1838

Namely, the relevant field seems to be an optional "currentStatus" key, and there's another "currentStatusUntil" field which has the time when the status will change. In phlay we'd probably want to check that in the USER case here, before (or perhaps after?) printing out the "Add Reviewer:" line.

https://github.com/mystor/phlay/blob/b7b26871cc56635dfac1f689659ed50b83e67c60/phlay#L875-L877

The code in that loop is getting kinda messy so it might also make sense to pull it out...
