### ISSUE TITLE
Doesn't set file modes for new files

### ISSUE THREAD

**Issue by glandium** [mystor/phlay#46]
I thought I've had that work in the past, but for some reason, it didn't happen for https://phabricator.services.mozilla.com/D16302 where taskcluster/scripts/misc/build-minidump-stackwalk.sh is missing the executable bit, that is properly set locally (otherwise, my try pushes would have blatantly failed).

**Comment by mystor** [comment]
Huh, that's super weird. I definitely see 100644 mode on the raw diff, which is wrong. Phlay should be preserving this information, though, the code for doing that definitely at least seems to still be there.

**Comment by glandium** [comment]
Happened again in https://phabricator.services.mozilla.com/D24322
