### ISSUE TITLE
Lando doesn't attribute authorship

### ISSUE THREAD

**Issue by glandium** [mystor/phlay#7]
As of writing, if I go to https://lando.services.mozilla.com/revisions/D4494/11320/, Details say:
```
Diff 11320 authored by Kris Maglione <...> on Wed, August 29, 2018, 7:03 AM GMT+9
    Accepted — By MattN
```
That one probably comes from arcanist or whatever.

However, if I go to https://phabricator.services.mozilla.com/D4200, Details say:
```
Diff 10507 authored by Unknown on Fri, August 24, 2018, 7:18 PM GMT+9
    Accepted — By jrmuizel
```

**Comment by mystor** [comment]
Thanks for letting me know :-) - I talked to smacleod and figured out that there is some commit information metadata which arcanist was sending and we aren't. I have a local version which I will push to send this data soon :-)

**Comment by mystor** [comment]
I've pushed a new version which works around that issue on the `diffparser` branch. I'd love feedback on how well it works.

Unfortunately, the diff parser I wrote doesn't handle renaming or copying files correctly yet, but I am hoping to fix that soon.

**Comment by mystor** [comment]
(fixing commit: f87e16887f8ffabfb21062340c7ccbef07dfb44d)
