### ISSUE TITLE
error cannot find user (constraints={'usernames': ['build']})

### ISSUE THREAD

**Issue by glandium** [mystor/phlay#8]
On phabricator, there's a firefox-build-system-reviewers group for build system reviews. By habit, I've tried `r?build` in my commits, but I also tried the full thing, and I couldn't find a value that would attribute the review to that group. And since it's not a really username, I also tried to change the constraint, but didn't find a constraint name that worked.

**Comment by mystor** [comment]
Currently phlay uses `user.search` to locate the user PHID for the reviewers. It appears as though I should either:
 1. Also check `project.search` to look up a project (like "build") by its slug, or
 2. Have some syntax for specifying that we want to look up a project by slug (e.g. `r?#build`)

@glandium Any thoughts on what you'd prefer?

**Comment by glandium** [comment]
3. Check `project.search` if `user.search` returned nothing?

**Comment by mystor** [comment]
@glandium Would you prefer that? It seems a bit awkward that if a username gets registered which conflicts with a project, it doesn't work out. I can totally handle it that way though.

**Comment by glandium** [comment]
When you type your r?whoever thing, you're pretty much expecting a single hit. If that matches a person, isn't it likely that's what you meant, rather than a project that might for some reason match at some level?
Stupid example: Say there's a project called "firefox-scripted-reviewers". Would you expect r?ted to ask Ted for review or ask you to disambiguate against "firefox-scripted-reviewers"?

**Comment by mystor** [comment]
Should be fixed on the diffparser branch in commit a49aa87b0d1c872a286706e84a69722bf57ed5fa
