### ISSUE TITLE
Pushing multiple commits from multiple bugs maybe should create a stack

### ISSUE THREAD

**Issue by glandium** [mystor/phlay#9]
I was pushing two commits for two bugs at once today, where one bug depends on the other. I think it's a common pattern. At least it is for me. It seems to me it would be better to add dependencies to the phabricator revisions when pushing multiple commits, even if they don't belong to the same bug.

**Comment by mystor** [comment]
I intentionally avoided creating these links before, but I've been convinced by various people that it was a poor decision :-). I'll probably add a flag you can specify to get back the no-dependencies-crossing-bugs behaviour (maybe `--isolate-bugs`?)

**Comment by mystor** [comment]
Should be fixed on the diffparser branch in 83b0383ec270371d620d3552a515757d11b484a2
